**Code to Genetrete Synthatic urls.:**

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU

# Define the Generator model
def build_generator(domain_length):
    model = Sequential()
    model.add(Dense(128, input_dim=100))
    model.add(LeakyReLU(alpha=0.01))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.01))
    model.add(Dense(domain_length, activation='sigmoid'))
    return model

# Get user input URL
user_input_url = input("Enter a URL: ")

# Extract domain name from user input URL
domain_name = user_input_url.split('//')[1].split('.')[0]

# Convert domain name to a format compatTible with model input
domain_length = len(domain_name)
domain_dataset = np.array([list(domain_name.encode())])

# Build the generator model
generator = build_generator(domain_length)

# Generate domain names and print in the same URL structure
def generate_and_print_domains(n_samples, generator, domain_length, original_url):
    noise = np.random.normal(0, 1, (n_samples, 100))
    generated_domains = generator.predict(noise)
    print(generated_domains[0])
    generated_domains_list = [
        "".join([chr(int(val * 26 + 97)) for val in domain]) # Convert values to letters
        for domain in generated_domains
    ]

    # Print generated domains with the same URL structure
    for generated_domain in generated_domains_list:
        generated_url = original_url.replace(domain_name, generated_domain)
        print(generated_url)
generate_and_print_domains(n_samples=100, generator=generator, domain_length=domain_length, original_url=user_input_url)

Enter a URL: https://colab.research.google.com/drive/1vwjmMsSW8pFrQgYipbTdmoD9FCzBW7W_
4/4 [==============================] - 0s 4ms/step
[[0.45401362 0.6492566  0.50229293 0.38635793 0.48743027]
 [0.4950973  0.6350895  0.39738077 0.58165514 0.62171197]
 [0.5417733  0.54341835 0.38986954 0.6757704  0.5530285 ]
 [0.32771328 0.68981206 0.4507127  0.630563   0.6474238 ]
 [0.51404655 0.64713234 0.30497146 0.6100177  0.66926396]
 [0.58150697 0.6187855  0.28919297 0.41073766 0.49671385]
 [0.5295008  0.604355   0.5350351  0.54914075 0.59393126]
 [0.53040165 0.67235786 0.359401   0.6648072  0.63622206]
 [0.48004776 0.55139136 0.410816   0.5889185  0.66290486]
 [0.55056024 0.5307343  0.52952445 0.68842065 0.6136724 ]
 [0.5013527  0.57659906 0.2848307  0.6775595  0.5267958 ]
 [0.45593467 0.5019508  0.41141117 0.63351285 0.45471254]
 [0.5355203  0.4474137  0.4298701  0.5585284  0.45282888]
 [0.45467138 0.63073474 0.43116453 0.5771806  0.4824202 ]
 [0.4243942  0.5641774  0.33454415 0.7024125  0.44